### ISSUE TITLE
Text file previews don't work with the theme installed

### ISSUE THREAD

**Issue by ixanza** [dracula/betterdiscord#21] opened 2022-08-18 05:28 UTC
Discord Version: Stable 142179 (8eea3ad)
BetterDiscord Version: 1.6.3

When the theme is enabled. Text file previews fail to render

![image](https://user-images.githubusercontent.com/5535758/185300965-be2722bf-bf0b-4b4b-84a6-60b1f95818c0.png)

Disabling the theme and restarting discord lets it render properly

![image](https://user-images.githubusercontent.com/5535758/185301013-439f13fa-bc03-441d-90b6-6fa9ecf53286.png)

**Comment by Kab1r** [comment] 2022-08-18 05:42
Hmm that's an odd bug

**Comment by ixanza** [comment] 2022-08-19 04:28
So an update on this. It seems once I disabled it and properly previewed a text file it works with the theme installed again. So I guess it just needed to render once before being themed?

![image](https://user-images.githubusercontent.com/5535758/185542956-6a3d8918-df60-40bc-ae9c-6b53df61e5ca.png)

**Comment by Kab1r** [comment] 2022-08-19 05:02
That makes more sense, maybe it's an issue with BetterDiscord

**Comment by mrhappyma** [comment] 2023-05-02 21:25
@ixanza is this still an issue?

**Comment by mrhappyma** [comment] 2023-06-04 18:58
I can't reproduce. Closing this.

**Closed by mrhappyma** 2023-06-04 18:58 UTC
